// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttceiihhgwajbrjulvay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0Y2VpaWhoZ3dhamJyanVsdmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDA4MzYsImV4cCI6MjA2MTIxNjgzNn0.siMzjng9UnaTq4a5KNiaKDXR86WGBqXtTFH188NHvFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);